all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: <yourPEMfilename>.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    validate_hosts: false
    #Enable JMX Exporter
    jmxexporter_enabled: true    
    env: aws
    # Allow 4-Letter Words to be used with Zookeeper 
    zookeeper_custom_properties:
      4lw.commands.whitelist: "*"
      
    # Kerberos / SSL configuration below  
    ssl_enabled: false
    ssl_mutual_auth_enabled: false
    sasl_protocol: kerberos
    kafka_broker_configure_additional_brokers: true

    zookeeper_sasl_protocol: kerberos

    kerberos_kafka_broker_primary: kafka
    kerberos_configure: true
    kerberos:
      realm: EXAMPLE.COM
      kdc_hostname: ec2-54-77-7-183.eu-west-1.compute.amazonaws.com
      admin_hostname: ec2-54-77-7-183.eu-west-1.compute.amazonaws.com

zookeeper:
  hosts:
    ip-10-0-14-78.eu-west-1.compute.internal:
      ansible_host: ec2-52-16-120-59.eu-west-1.compute.amazonaws.com
      zookeeper_id: 1
      zookeeper_kerberos_keytab_path: "/tmp/zookeeper.service.keytab"
      zookeeper_kerberos_principal: "zookeeper/ec2-52-16-120-59.eu-west-1.compute.amazonaws.com@EXAMPLE.COM"

kafka_broker:
  hosts:
    ip-10-0-13-33.eu-west-1.compute.internal:
      ansible_host: ec2-52-211-77-186.eu-west-1.compute.amazonaws.com
      kafka_broker_custom_properties:
        # Specifying broker.rack for rack awareness
        broker.rack: eu-west-1a
        broker_id: 1
        kafka_broker_kerberos_keytab_path: "/tmp/kafka.service.keytab"
        kafka_broker_kerberos_principal: "kafka/ec2-52-211-77-186.eu-west-1.compute.amazonaws.com@EXAMPLE.COM"