all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: <yourPEMfilename>.pem
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    validate_hosts: false
    # Uses Ubuntu 20.04 LTS (focal)
    confluent_common_repository_debian_release_version: focal
    # Enable JMX Exporter
    jmxexporter_enabled: true    
    env: aws
    # Allow 4-Letter Words to be used with Zookeeper 
    zookeeper_custom_properties:
      4lw.commands.whitelist: "*"

zookeeper:
  hosts:
    ip-xxx-xxx-xxx-xxx.aws-region.compute.internal:
      ansible_host: ec2-xxx-xxx-xxx-xxx.aws-region.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-xxx-xxx-xxx-xxx.aws-region.compute.internal:
      ansible_host: ec2-xxx-xxx-xxx-xxx.aws-region.compute.amazonaws.com
      kafka_broker_custom_properties:
        # Specifying broker.rack for rack awareness
        broker.rack: eu-west-1a

control_center:
  hosts:
    ip-xxx-xxx-xxx-xxx.aws-region.compute.internal:
      ansible_host: ec2-xxx-xxx-xxx-xxx.aws-region.compute.amazonaws.com
